= HC SDK Integration Test Suite

image:https://github.com/d4l-data4life/hc-sdk-kmp-integration/workflows/D4L%20CI%20-%20Login%20verification/badge.svg[Build Status,link=https://github.com/d4l-data4life/hc-sdk-android-integration/actions?query=workflow%3A%22D4L+CI+Android+-+Login+verification%22]

This is an integration of the link:https://github.com/d4l-data4life/hc-sdk-kmp[D4L SDK] for testing purposes.

A suite of UI tests to identify breaking changes and regressions by SDK version changes.

== Requirements

* Android 6.0 (API 23) to Android 12L (API 32)
* Kotlin 1.6.21
* Java 11

== Dependencies

* link:https://github.com/d4l-data4life/hc-sdk-kmp[D4L SDK]

== Usage

Before you start you need to add `d4l-client-config-android.json` and `d4l-test-config-android.json` files in the project root folder and add following content.

`d4l-client-config-android.json` needs to contain a config for every environment LOCAL, DEVELOPMENT, STAGING, SANDBOX, PRODUCTION.

NOTE: The CI expects this configuration from environment variables stored in GitHub secrets: `D4L_CLIENT_CONFIG_ANDROID` and `D4L_CLIENT_CONFIG_IOS`

[source,json,d4l-client-config-android.json]
----
// d4l-client-config-android.json
{
  "configs": {
    "LOCAL": {
      "id": "{CLIENT_ID}",
      "secret": "{CLIENT_SECRET}",
      "redirectScheme": "{CLIENT_REDIRECT_SCHEME}"
    },
    "DEVELOPMENT": {
      "id": "{CLIENT_ID}",
      "secret": "{CLIENT_SECRET}",
      "redirectScheme": "{CLIENT_REDIRECT_SCHEME}"
    }
  }
}
----

[source,json,d4l-test-config-android.json]
----
// d4l-test-config-android.json
{
  "user": {
    "email": "{USER_EMAIL}",
    "password": "{USER_PASSWORD}",
    "phoneCountryCode": "{USER_PHONE_COUNTRY_CODE}",
    "phoneLocalNumber": "{USER_PHONE_LOCAL_NUMBER}"
  },
   "sinch": {
      "servicePlanId": "{SERVICE_PLAN_ID}",
      "authToken": "{AUTH_TOKEN}"
    }
}
----

Run gradle wrapper task for connected tests:

[source,bash]
----
./gradlew provideTestConfig
./gradlew connectedAndroidTest
----

== Test suit

* [x] Login
* [x] Logout
* [x] AppData CRUD + count
* [x] FHIR 3 and FHIR 4 Document CRUD + count
