= HC SDK Integration Test Suit

image:https://github.com/d4l-data4life/hc-sdk-android-integration/workflows/D4L%20CI%20Android/badge.svg[Build Status,link=https://github.com/d4l-data4life/hc-sdk-android-integration/actions?query=workflow%3A%22D4L+CI+Android%22] image:https://github.com/d4l-data4life/hc-sdk-android-integration/workflows/D4L%20CI%20Android%20-%20Login%20verification/badge.svg[Build Status,link=https://github.com/d4l-data4life/hc-sdk-android-integration/actions?query=workflow%3A%22D4L+CI+Android+-+Login+verification%22]

This is an Android integration of the link:https://github.com/d4l-data4life/hc-sdk-kmp[D4L SDK] for testing purposes.

A suit of UI tests to identify breaking changes and regressions by SDK version changes.

== Requirements

* Android 5.0.1 (API 21) to Android 10 (API 29)
* Kotlin 1.4.10
* Java 8 link:https://developer.android.com/studio/write/java8-support[Limitations] https://jakewharton.com/d8-library-desugaring/[Desugaring]
* Android Emulator 21 - 29
* Gradle 6.7.1
* link:https://developer.android.com/studio#downloads[Android Studio 4.1.1]

== Dependencies

* link:https://github.com/d4l-data4life/hc-sdk-kmp[D4L SDK]
* link:https://github.com/d4l-data4life/hc-fhir-java[D4L FHIR SDK]
* link:https://github.com/d4l-data4life/hc-fhir-helper-kmp[D4L FHIR Helper SDK]
* link:https://github.com/d4l-data4life/hc-util-kmp[D4L Util SDK]

== Usage

Before you start you need to add `d4l-client-config-android.json` and `d4l-test-config-android.json` files in the project root folder and add following content.

`d4l-client-config-android.json` needs to contain a config for every environment LOCAL, DEVELOPMENT, STAGING, SANDBOX, PRODUCTION.

NOTE: The CI expects this configuration from environment variables stored in GitHub secrets: `D4L_CLIENT_CONFIG_ANDROID` and `D4L_CLIENT_CONFIG_IOS`

[source,json,d4l-client-config-android.json]
----
// d4l-client-config-android.json
{
  "configs": {
    "LOCAL": {
      "id": "{CLIENT_ID}",
      "secret": "{CLIENT_SECRET}",
      "redirectScheme": "{CLIENT_REDIRECT_SCHEME}"
    },
    "DEVELOPMENT": {
      "id": "{CLIENT_ID}",
      "secret": "{CLIENT_SECRET}",
      "redirectScheme": "{CLIENT_REDIRECT_SCHEME}"
    }
  }
}
----

[source,json,d4l-test-config-android.json]
----
// d4l-test-config-android.json
{
  "user": {
    "email": "{USER_EMAIL}",
    "password": "{USER_PASSWORD}",
    "phoneCountryCode": "{USER_PHONE_COUNTRY_CODE}",
    "phoneLocalNumber": "{USER_PHONE_LOCAL_NUMBER}"
  },
  "twillio": {
    "accountSid": "{TWILLIO_ACCOUNT_SID}",
    "authSid": "{TWILLIO_AUTH_SID}",
    "authToken": "{TWILLIO_AUTH_TOKEN}"
  }
}
----

Run gradle wrapper task for connected tests:

[source,bash]
----
./gradlew provideAndroidTestConfig
./gradlew connectedAndroidTest
----

== Test suit

* [x] Login
* [x] Logout
* [ ] Document CRUD
* [ ] Report CRUD
* [ ] Observation CRUD
* [ ] Fetch record by type
* [ ] Count total records
* [ ] Count records per type
