name: Android CI (MacMini)

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  build:

    runs-on: [self-hosted, macos]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1.0.3
        id: cache-gradle
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Start emulator and wait for it
        run: ./script/ci/android/start_and_wait_for_emulator.sh
      - name: Cleanup
        run: ./gradlew clean
      - name: Rund checks
        run: ./gradlew check
      - name: Run End2End Tests
        run: ./gradlew connectedAndroidTest
