name: Android CI (MacMini)

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  build:

    runs-on: [self-hosted, macos]

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
      - name: Start emulator and wait for it
        run: ./script/ci/android/prepare_start_and_wait_for_emulator.sh
      - name: Cleanup
        run: ./gradlew clean
      - name: Rund checks
        run: ./gradlew check
      - name: Run End2End Tests
        run: ./gradlew connectedAndroidTest
